---
- name: Template Mailhog configuration
  ansible.builtin.template:
    src: rc.conf.d/mailhog.j2
    dest: /usr/local/etc/rc.conf.d/mailhog
    owner: "root"
    mode: "0644"
  notify: Restart MailHog
