---
- name: Template nginx configuration
  ansible.builtin.template:
    src: "nginx/http.d/mailhog.conf.j2"
    dest: "{{ nginx.prefix.config }}/http.d/mailhog.conf"
    mode: "0644"
    owner: "root"
  notify: Reload nginx
